#!/bin/sh

# Xcode Cloud clones the repository without the generated `.xcodeproj` (it is
# gitignored and produced by XcodeGen). Regenerate it here, after the clone and
# before Xcode Cloud resolves packages and builds.

set -e

cd "$CI_PRIMARY_REPOSITORY_PATH"

# The Apple Team ID is kept out of version control. Materialize the gitignored
# signing xcconfig from the DEVELOPMENT_TEAM environment variable (set it as an
# Xcode Cloud environment variable). Falls back to empty so generation never fails.
if [ ! -f Config/Signing.xcconfig ]; then
  echo "Writing Config/Signing.xcconfig from \$DEVELOPMENT_TEAM…"
  mkdir -p Config
  {
    echo "// Generated by ci_post_clone.sh from the DEVELOPMENT_TEAM environment variable."
    echo "DEVELOPMENT_TEAM = ${DEVELOPMENT_TEAM:-}"
  } > Config/Signing.xcconfig
fi

echo "Installing XcodeGen…"
brew install xcodegen

echo "Generating Xcode project…"
xcodegen generate

echo "Done."
