#!/bin/sh

# Xcode Cloud clones the repository without the generated `.xcodeproj` (it is
# gitignored and produced by XcodeGen). Regenerate it here, after the clone and
# before Xcode Cloud resolves packages and builds.

set -e

cd "$CI_PRIMARY_REPOSITORY_PATH"

# The Apple Team ID is kept out of version control. Materialize the gitignored
# local signing override from the DEVELOPMENT_TEAM environment variable (set it as
# an Xcode Cloud environment variable). Config/Signing.xcconfig is a committed stub
# that optionally includes this file.
if [ ! -f Config/Signing.local.xcconfig ]; then
  echo "Writing Config/Signing.local.xcconfig from \$DEVELOPMENT_TEAM…"
  mkdir -p Config
  {
    echo "// Generated by ci_post_clone.sh from the DEVELOPMENT_TEAM environment variable."
    echo "DEVELOPMENT_TEAM = ${DEVELOPMENT_TEAM:-}"
  } > Config/Signing.local.xcconfig
fi

echo "Installing XcodeGen…"
brew install xcodegen

echo "Generating Xcode project…"
xcodegen generate

echo "Done."
